name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}] # roda todo domingo
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 5
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_stars: yes
